wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1651425072
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      4: 3.10.2
      5: 0.12.15
      8:
      - 1
      - 3
      - 5
